/* GENERATED by tools/wallsheet.py from wall-layout.txt.
   Do not edit — edit the .txt and re-run the tool. This file and
   demos/models/*.jpg come out of the same run, which is the only
   thing keeping the baked pixels and this cell -> game map in step.

   `python3 tools/wallsheet.py --check` fails if this file does not
   match the layout, which is what CI runs. */
const WALL_SHEET_V="59ab85a6";
const WALL_ZONES={
  "wall":{zone:1,sheet:"wall",cols:4,rows:3,plate:true,aspect:2.176871,titles:["Netcode Battle","Netcode Demo","Netcode Shooter2D","Game2d Black Ops","POLYGON Battle","POLYGON Adventure","POLYGON Turnbase","Game3d Racing","Kinder Easter","AAF","Joust them all"]},
  "wallL":{zone:8,sheet:"wall-left",cols:1,rows:3,plate:false,aspect:0.544218,titles:["Beat'em up","Beat'em up 2","Topdown Shooter"]},
  "wallR":{zone:9,sheet:"wall-right",cols:1,rows:4,plate:false,aspect:0.408163,titles:["Game Runner 3d","Cardgame Battle 2d","Battle Board 2d","Game 2d5 Dungeon"]},
};
/* title -> the .mp4 in demos/clips/ that previews it, for every build
   that has one. A map rather than a set of ids because the id is this
   tool's business: the room used to carry its own copy of the slug
   rule so it could turn a title into a filename and hope the two
   agreed. Now it looks the answer up. Baked by tools/clips.py,
   enumerated from what is actually on disk so the two cannot
   disagree — a miss would be a 404 on every hover of that cover. */
const CLIP_OF={
  "Kinder Easter":"kinder-easter",
  "AAF":"aaf",
  "AR demo":"ar-demo",
  "Netcode Battle":"netcode-battle",
  "Netcode Shooter2D":"netcode-shooter2d",
  "Netcode Demo":"netcode-demo",
  "Color Shoot 2d":"color-shoot-2d",
  "Math Game 2d":"math-game-2d",
  "Find Monkey 2d":"find-monkey-2d",
  "POLYGON Battle":"polygon-battle",
  "POLYGON Turnbase":"polygon-turnbase",
  "POLYGON Adventure":"polygon-adventure",
  "Game Runner 3d":"game-runner-3d",
  "Game Shooter 2d":"game-shooter-2d",
  "Joust them all":"joust-them-all",
  "Cardgame Battle 2d":"cardgame-battle-2d",
  "Battle Board 2d":"battle-board-2d",
  "Demo Dental 3d":"demo-dental-3d",
  "Subway Clone 3d":"subway-clone-3d",
  "Survivor.io clone 2d":"survivor-io-clone-2d",
  "Beat'em up":"beat-em-up",
  "Beat'em up 2":"beat-em-up-2",
  "Archer 2d":"archer-2d",
  "Game Nightmares":"game-nightmares",
  "City zombie":"city-zombie",
  "Topdown Shooter":"topdown-shooter",
  "Game 2d5 Dungeon":"game-2d5-dungeon",
  "Shoot ball 3d":"shoot-ball-3d",
  "Endless car 3d":"endless-car-3d",
  "Jump 2d":"jump-2d",
};
/* The props that carry a list of builds. A rule is evaluated in the
   room against live data; a list is taken as written. */
const ROOM_LISTS={
  "casual":{name:"trash",titles:["Archer 2d","Jump 2d","Math Game 2d","Find Monkey 2d","Game Shooter 2d","Color Shoot 2d"]},
  "monR":{name:"monitor",auto:{section:"RESKIN"}},
  "ar":{name:"tablet",auto:{section:"AR Games"}},
  "holo":{name:"showreel",auto:{link:"Youtube"}},
};
